name: SonarCloud Review

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/Api/Api.csproj

      - name: Build project
        run: dotnet build ./backend/Api/Api.csproj --no-restore --configuration Release

      - name: Run tests with coverage
        run: dotnet test ./backend/Api/Api.csproj --no-build --collect:"XPlat Code Coverage"

      - name: Convert coverage to OpenCover
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage -reporttypes:SonarQube
          mv coverage/SonarQube.xml coverage.opencover.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: thieuquochuy
          projectKey: ThieuQuocHuy_Project_TemPlate_KTPM
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
